"""SKiDL schematic for design 'desk-bike' generated by wirestudio.

To produce a .kicad_sch (KiCad 6+), install SKiDL and run this file:

    pip install skidl
    python desk-bike.skidl.py

The script writes <design_id>.kicad_sch + .net + .xml into the current
directory. Edit pin assignments + component overrides above the
generate_*() calls if you want to tweak before re-running.
"""
import glob
import os
import re

import skidl
from skidl import Part, Net, generate_netlist, generate_schematic, TEMPLATE


def _kicad8_compat():
    # SKiDL 2.2.x's kicad8 writer emits two KiCad 9 constructs that
    # KiCad 8's parser rejects: the nested (pin_numbers (hide yes)) form
    # (8 requires the bare (pin_numbers hide)) and the embedded_fonts
    # token (unknown to 8). Rewrite the emitted file to 8's grammar.
    for path in glob.glob("*.kicad_sch"):
        with open(path) as fh:
            text = fh.read()
        text = re.sub(r"\(pin_numbers\s*\(hide yes\)\s*\)", "(pin_numbers hide)", text)
        text = re.sub(r"\(pin_numbers\s*\(hide no\)\s*\)", "", text)
        text = re.sub(r"\(embedded_fonts\s+(?:yes|no)\)", "", text)
        with open(path, "w") as fh:
            fh.write(text)

# Pin the tool and symbol search path so the script resolves symbols the
# same way everywhere it runs. SKiDL's default tool predates .kicad_sym
# libraries, and its default search path includes '.', which lets a stray
# <Lib>.kicad_sym in the tree shadow the real library.
skidl.set_default_tool(skidl.KICAD8)
_sym = next((os.environ[v] for v in (
    "KICAD8_SYMBOL_DIR", "KICAD9_SYMBOL_DIR", "KICAD7_SYMBOL_DIR",
    "KICAD6_SYMBOL_DIR", "KICAD_SYMBOL_DIR") if os.environ.get(v)), None)
if _sym:
    skidl.lib_search_paths[skidl.KICAD8] = [_sym]


def build():
    # ---- Power rails -----------------------------------------------------
    # Power nets draw as short labeled stubs at each pin instead of
    # routed wires -- standard schematic practice, and it keeps SKiDL's
    # router from webbing the sheet with power wiring.
    GND = Net("GND")
    GND.stub = True
    NET_PLUS__3V3 = Net("+3V3")
    NET_PLUS__3V3.stub = True
    NET_PLUS__5V = Net("+5V")
    NET_PLUS__5V.stub = True

    # ---- Component instances --------------------------------------------
    # Board: ESP32-DevKitC-V4
    board = Part("RF_Module", "ESP32-WROOM-32", ref="M1", footprint="RF_Module:ESP32-WROOM-32")
    # oled (SSD1306 / SH1106 OLED display (I2C))
    c_oled = Part("Connector_Generic", "Conn_01x05", ref="U1", value="SSD1306", footprint="Connector_PinHeader_2.54mm:PinHeader_1x05_P2.54mm_Vertical")
    # dial (Quadrature rotary encoder (KY-040 style))
    c_dial = Part("Device", "RotaryEncoder", ref="U2", value="Rotary encoder", footprint="Rotary_Encoder:RotaryEncoder_Alps_EC11E_Vertical_H20mm")
    # btn_push (Generic GPIO binary sensor)
    c_btn_push = Part("Connector_Generic", "Conn_01x02", ref="U3", value="Input", footprint="Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical")
    # btn_back (Generic GPIO binary sensor)
    c_btn_back = Part("Connector_Generic", "Conn_01x02", ref="U4", value="Input", footprint="Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical")
    # btn_confirm (Generic GPIO binary sensor)
    c_btn_confirm = Part("Connector_Generic", "Conn_01x02", ref="U5", value="Input", footprint="Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical")
    # brake_pot (Generic analog input)
    c_brake_pot = Part("Connector_Generic", "Conn_01x01", ref="U6", value="ADC sense", footprint="Connector_PinHeader_2.54mm:PinHeader_1x01_P2.54mm_Vertical")
    # crank_reed (Pulse counter / tachometer (RPM, flow, energy))
    c_crank_reed = Part("Connector_Generic", "Conn_01x02", ref="U7", value="Pulse source", footprint="Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical")
    # bridge.q_hi_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_hi_a)
    c_bridge_q_hi_a = Part("Transistor_FET", "IRF4905", ref="Q1", value="IRF4905", footprint="Package_TO_SOT_THT:TO-220-3_Vertical")
    # bridge.q_lo_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_lo_a)
    c_bridge_q_lo_a = Part("Transistor_FET", "IRLZ44N", ref="Q2", value="IRFZ44N", footprint="Package_TO_SOT_THT:TO-220-3_Vertical")
    # bridge.q_drv_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_drv_a)
    c_bridge_q_drv_a = Part("Transistor_BJT", "2N3904", ref="Q3", value="2N3904", footprint="Package_TO_SOT_THT:TO-92_Inline")
    # bridge.r_gate_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_gate_a)
    c_bridge_r_gate_a = Part("Device", "R", ref="R1", value="470", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.r_base_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_base_a)
    c_bridge_r_base_a = Part("Device", "R", ref="R2", value="1k", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.r_pd_a (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_pd_a)
    c_bridge_r_pd_a = Part("Device", "R", ref="R3", value="10k", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.q_hi_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_hi_b)
    c_bridge_q_hi_b = Part("Transistor_FET", "IRF4905", ref="Q4", value="IRF4905", footprint="Package_TO_SOT_THT:TO-220-3_Vertical")
    # bridge.q_lo_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_lo_b)
    c_bridge_q_lo_b = Part("Transistor_FET", "IRLZ44N", ref="Q5", value="IRFZ44N", footprint="Package_TO_SOT_THT:TO-220-3_Vertical")
    # bridge.q_drv_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): q_drv_b)
    c_bridge_q_drv_b = Part("Transistor_BJT", "2N3904", ref="Q6", value="2N3904", footprint="Package_TO_SOT_THT:TO-92_Inline")
    # bridge.r_gate_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_gate_b)
    c_bridge_r_gate_b = Part("Device", "R", ref="R4", value="470", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.r_base_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_base_b)
    c_bridge_r_base_b = Part("Device", "R", ref="R5", value="1k", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.r_pd_b (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): r_pd_b)
    c_bridge_r_pd_b = Part("Device", "R", ref="R6", value="10k", footprint="Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal")
    # bridge.c_bulk (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): c_bulk)
    c_bridge_c_bulk = Part("Device", "C_Polarized", ref="C1", value="470uF", footprint="Capacitor_THT:CP_Radial_D8.0mm_P3.50mm")
    # bridge.c_motor (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): c_motor)
    c_bridge_c_motor = Part("Device", "C", ref="C2", value="100nF", footprint="Capacitor_THT:C_Disc_D5.0mm_W2.5mm_P5.00mm")
    # bridge.j_motor (Discrete MOSFET H-bridge (IRF4905 / IRFZ44N, 5 V): j_motor)
    c_bridge_j_motor = Part("Connector_Generic", "Conn_01x02", ref="J1", value="Motor", footprint="TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2_1x02_P5.00mm_Horizontal")

    # ---- Buses ----------------------------------------------------------
    NET_BUS_i2c0 = Net("BUS_i2c0")  # i2c bus

    # ---- Connections ----------------------------------------------------
    c_oled["1"] += NET_PLUS__3V3
    c_oled["2"] += GND
    c_oled["3"] += NET_BUS_i2c0
    c_oled["4"] += NET_BUS_i2c0
    c_dial["A"] += Net("GPIO_GPIO16")
    c_dial["B"] += Net("GPIO_GPIO17")
    c_btn_push["1"] += Net("GPIO_GPIO25")
    c_btn_back["1"] += Net("GPIO_GPIO26")
    c_btn_confirm["1"] += Net("GPIO_GPIO33")
    c_brake_pot["1"] += Net("GPIO_GPIO34")
    c_crank_reed["1"] += Net("GPIO_GPIO27")
    # bridge: subcircuit
    n_bridge_gate_a = Net("bridge_gate_a")
    n_bridge_out_a = Net("bridge_out_a")
    n_bridge_base_a = Net("bridge_base_a")
    n_bridge_IN1 = Net("GPIO_GPIO18")
    n_bridge_gate_b = Net("bridge_gate_b")
    n_bridge_out_b = Net("bridge_out_b")
    n_bridge_base_b = Net("bridge_base_b")
    n_bridge_IN2 = Net("GPIO_GPIO19")
    c_bridge_q_hi_a["G"] += n_bridge_gate_a
    c_bridge_q_hi_a["D"] += n_bridge_out_a
    c_bridge_q_hi_a["S"] += NET_PLUS__5V
    c_bridge_q_lo_a["G"] += n_bridge_gate_a
    c_bridge_q_lo_a["D"] += n_bridge_out_a
    c_bridge_q_lo_a["S"] += GND
    c_bridge_q_drv_a["C"] += n_bridge_gate_a
    c_bridge_q_drv_a["B"] += n_bridge_base_a
    c_bridge_q_drv_a["E"] += GND
    c_bridge_r_gate_a["1"] += NET_PLUS__5V
    c_bridge_r_gate_a["2"] += n_bridge_gate_a
    c_bridge_r_base_a["1"] += n_bridge_IN1
    c_bridge_r_base_a["2"] += n_bridge_base_a
    c_bridge_r_pd_a["1"] += n_bridge_IN1
    c_bridge_r_pd_a["2"] += GND
    c_bridge_q_hi_b["G"] += n_bridge_gate_b
    c_bridge_q_hi_b["D"] += n_bridge_out_b
    c_bridge_q_hi_b["S"] += NET_PLUS__5V
    c_bridge_q_lo_b["G"] += n_bridge_gate_b
    c_bridge_q_lo_b["D"] += n_bridge_out_b
    c_bridge_q_lo_b["S"] += GND
    c_bridge_q_drv_b["C"] += n_bridge_gate_b
    c_bridge_q_drv_b["B"] += n_bridge_base_b
    c_bridge_q_drv_b["E"] += GND
    c_bridge_r_gate_b["1"] += NET_PLUS__5V
    c_bridge_r_gate_b["2"] += n_bridge_gate_b
    c_bridge_r_base_b["1"] += n_bridge_IN2
    c_bridge_r_base_b["2"] += n_bridge_base_b
    c_bridge_r_pd_b["1"] += n_bridge_IN2
    c_bridge_r_pd_b["2"] += GND
    c_bridge_c_bulk["1"] += NET_PLUS__5V
    c_bridge_c_bulk["2"] += GND
    c_bridge_c_motor["1"] += n_bridge_out_a
    c_bridge_c_motor["2"] += n_bridge_out_b
    c_bridge_j_motor["1"] += n_bridge_out_a
    c_bridge_j_motor["2"] += n_bridge_out_b


if __name__ == "__main__":
    build()
    # Default: emit a netlist (.net) + a schematic (.kicad_sch).
    # Comment out either if you only want one.
    generate_netlist()
    # allow_routing_failure: SKiDL's schematic router is best-effort; a
    # degraded render with stubbed nets beats no render at all.
    # auto_stub: high-fanout nets (buses) become labeled stubs, and
    # routing failures fall back to a stubbed drawing instead of raising.
    # rotate_parts: the placer may orient parts to shorten wiring.
    generate_schematic(allow_routing_failure=True, auto_stub=True, rotate_parts=True)
    _kicad8_compat()
